# Generated by Django 3.1.2 on 2021-02-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Electronic', 'Electronic')], max_length=10, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('N', 'New'), ('T', 'Trending'), ('X', 'Excel')], max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pcolor', models.CharField(blank=True, choices=[('RED', 'RED'), ('White', 'White'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Blue', 'Blue')], max_length=10)),
                ('psize', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
