# Generated by Django 3.1.2 on 2021-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
