# Generated by Django 3.1.2 on 2021-02-10 10:27

import all_users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0002_auto_20210210_0701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', all_users.models.UserManager()),
            ],
        ),
    ]
