# Generated by Django 3.1.2 on 2021-02-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0003_auto_20210212_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrequest',
            name='phone_no',
        ),
    ]
