# Generated by Django 3.1.2 on 2021-02-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0003_auto_20210210_1027'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
