# Generated by Django 3.1.2 on 2021-02-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0004_remove_staffrequest_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
